export const data = [
    {
        id:1,
        userID:'57sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:2,
        userID:'55sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:3,
        userID:'57sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:4,
        userID:'55sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:5,
        userID:'57sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:6,
        userID:'55sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:7,
        userID:'57sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:8,
        userID:'55sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:9,
        userID:'57sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:10,
        userID:'55sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:11,
        userID:'57sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:12,
        userID:'55sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:13,
        userID:'57sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:14,
        userID:'55sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:15,
        userID:'57sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:16,
        userID:'55sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:17,
        userID:'57sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:18,
        userID:'55sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:19,
        userID:'57sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
    {
        id:20,
        userID:'55sw78',
        fullName:'Artur Grigoryan',
        text:'sdjsj skdlsjd sdljasjds ljksdowjd skdjiwdask isdiwjfa jsjd',
        url:'https://img.freepik.com/free-photo/no-problem-concept-bearded-man-makes-okay-gesture-has-everything-control-all-fine-gesture-wears-spectacles-jumper-poses-against-pink-wall-says-i-got-this-guarantees-something_273609-42817.jpg?size=626&ext=jpg',
    },
]